export const TIME_SECOND_IN_SECONDS = 1;
export const TIME_MINUTE_IN_SECONDS = TIME_SECOND_IN_SECONDS * 60;
export const TIME_HOUR_IN_SECONDS = TIME_MINUTE_IN_SECONDS * 60;
export const TIME_DAY_IN_SECONDS = TIME_HOUR_IN_SECONDS * 24;
export const TIME_WEEK_IN_SECONDS = TIME_DAY_IN_SECONDS * 7;
export const TIME_MONTH_IN_SECONDS = TIME_DAY_IN_SECONDS * 30;
export const TIME_YEAR_IN_SECONDS = TIME_DAY_IN_SECONDS * 365;
export const TIME_FOREVER_IN_SECONDS = TIME_YEAR_IN_SECONDS * 99; // actually 99 years, but close enough

export const TIME_SECOND_IN_MILLISECONDS = TIME_SECOND_IN_SECONDS * 1000;
export const TIME_MINUTE_IN_MILLISECONDS = TIME_MINUTE_IN_SECONDS * 1000;
export const TIME_HOUR_IN_MILLISECONDS = TIME_HOUR_IN_SECONDS * 1000;
export const TIME_DAY_IN_MILLISECONDS = TIME_DAY_IN_SECONDS * 1000;
export const TIME_WEEK_IN_MILLISECONDS = TIME_WEEK_IN_SECONDS * 1000;
export const TIME_MONTH_IN_MILLISECONDS = TIME_MONTH_IN_SECONDS * 1000;
export const TIME_YEAR_IN_MILLISECONDS = TIME_YEAR_IN_SECONDS * 1000;
export const TIME_FOREVER_IN_MILLISECONDS = TIME_FOREVER_IN_SECONDS * 1000;
